openapi: 3.0.0
info:
  title: LumRPi API
  version: 1.0.0
servers:
  - url: http://lumrpi.local
paths:
  /status:
    get:
      tags:
        - default
      summary: Get status
      description: Récupère la config, les animations en cours sur les tables, etc.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /flag:
    post:
      tags:
        - default
      summary: Jouer flag
      description: >-
        Joue un petit son et allume progressivement le bandeau de l'équipe en
        vert.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                table: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /box:
    post:
      tags:
        - default
      summary: Pwn box
      description: >-
        Jouer le son "L'équipe n°X vient pwn la box !", le bandeau passe en mode
        arc-en-ciel pour le reste du round.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                table: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /round:
    post:
      tags:
        - default
      summary: Démarrer un round
      description: >-
        - Jouer le son "Début du round n°X"
            
        - Faire une animation de début de round sur le bandeau de la salle
            
        - Reset l'état de toutes les tables pour revenir à l'animation au repos
        (vague rose)
            
        - Prévenir (animation sur le bandeau de la salle + son) quand il reste 5
        min
            
        - Prévenir (animation sur le bandeau de la salle + son) quand il reste 1
        min
            
        - Le paramètre _duration_ est la durée du round en minutes, il est
        facultatif.
            
        - A la fin du round, le bandeau est freeze (plus de changement de pixel)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                round: 1
                duration: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forceColor:
    post:
      tags:
        - default
      summary: Forcer couleur
      description: >-
        Forcer la couleur de toutes les tables (#000000 permet d'éteindre le
        bandeau). Si une durée (en minutes) est précisée, les animations
        reprennent une fois le temps écoulé.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                duration: 1
                color: '#ff0000'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
